app = "kesha-finance-bot"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "bot/Dockerfile"

[[services]]
  internal_port = 8080

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
